ForwardList:
  Accounts:             # Account id for each bot in ForwardList
    QQ: 12213312        # your QQ bot account number
    Telegram: 12321312  # your telegram bot chat id
  Topology:  # delete this key if empty
    # Topology contains all the point to point forward:
    # E.g. From one QQ group to one telegram group, type = OneWay+
    - From: QQ
      FromChat: 1123131231
      FromChatType: group  # group, discuss, private
      To: Telegram
      ToChat: -31231212344  # telegram chat id, use !!id to show
      ToChatType: group
      ForwardType: OneWay+
      # OneWay:
      # Forward from "FromChat" to "ToChat"
      # BiDirection:
      # Forward from "FromChat" to "ToChat" and vise versa
      # OneWay+:
      # Forward from "FromChat" to "ToChat", and vise versa, ignoring backward message without "reply_to"
  Default:  # delete this key if empty
    # Default contains all the platform to point forward:
    # E.g. Any message originated from QQ to one telegram group, type = OneWay+
    - From: QQ
      To: Telegram
      ToChat: 123244234234
      ToChatType: group
      ForwardType: OneWay+
      # OneWay:
      # Forward from "FromChat" to "ToChat"
      # OneWay+:
      # Forward from "FromChat" to "ToChat", and vise versa, ignoring backward message without "reply_to"
Extensions:  # Extensions to load
  - umr_telegram_driver
  - umr_line_driver
  - umr_discord_driver
  - umr_coolq_driver
  - umr_mirai_driver
  - umr_extensions_demo
Driver:
  QQ:
    Base: QQ
    Account: 643503161
    APIRoot: http://127.0.0.1:5700/
    ListenIP: 172.17.0.1
    ListenPort: 8080
    Token: very
    Secret: long
    NameforPrivateChat: yes   # if destination chat_id is a private chat, show all attributes (sender name, reply to, forward from)
    NameforGroupChat: yes     # if destination chat_id is a group/discuss chat, show all attributes (sender name, reply to, forward from)
  Telegram:
    Base: Telegram
    BotToken: asdasdsadsadsadsad
    # HTTPProxy: http://127.0.0.1:1080  # uncomment f proxy is required
  Line:
    Base: Line
    ChannelID: sdarq3rcar323r2r23r
    BotToken: 123dff23rr23r23r23rr
    WebHookToken: 43r23r23rf23r23r23r2
    WebHookURL: https://example.com  # must not include /callback
    WebHookPort: 41443
    HTTPSCert: /root/.acme.sh/example.com/example.com.cer
    HTTPSKey: /root/.acme.sh/example.com/example.com.key
    HTTPSCA: /root/.acme.sh/example.com/ca.cer
  Discord:
    Base: Discord
    BotToken: asdsadsddfffsdffsdfsd  # the longer one
    ClientToken: asdasdsadsfsafsdfsd # the shorter one
  Mirai:
    Base: Mirai
    Account: 1213123
    Host: 127.0.0.1
    Port: 18080
    AuthKey: abcdefgh
    NameforPrivateChat: yes   # if destination chat_id is a private chat, show all attributes (sender name, reply to, forward from)
    NameforGroupChat: yes     # if destination chat_id is a group/discuss chat, show all attributes (sender name, reply to, forward from)

DataRoot: /root/coolq/data/image
LogRoot: /var/log/umr
CommandPrefix: "!!"  # optional, default "!!"
BotAdmin:            # optional, default empty
  QQ:
    - 123456789
    - 987654321
  Telegram:
    - 213442352354534534
    - 345235345345345345
LogLevel:           # Optional, default DEBUG
  '*': DEBUG        # Global level
  httpx: INFO       # Module level
  aiogram: INFO
  asyncio: INFO
