version: '3'
services:
  ctb:
    build: '.'
    depends_on: 
      - cqhttp
    env_file: dc_settings.env
    volumes:
      - "${CQ_DATA}:/home/user/coolq"
    environment:
      - 'CTB_JSON_SETTINGS_PATH'
  cqhttp:
    image: richardchien/cqhttp:latest
    ports:
      -'${VNC_PORT}:9000'
    env_file: dc_settings.env
    volumes:
      - "${CQ_DATA}:/home/user/coolq"