version: '3'
services:
  ctb:
    build: '.'
    depends_on: 
      - cqhttp
    env_file: .env
    volumes:
      - '${CQ_DATA_PATH}:/home/user/coolq'
    restart: always

  # richardchien/cqhttp
  cqhttp:
    image: richardchien/cqhttp:latest
    env_file: .env
    ports:
      - ${VNC_PORT}:9000
    volumes:
      - '${CQ_DATA_PATH}:/home/user/coolq'
      - ./plugins/conf:/usr/src/app/plugins/conf
    restart: always
    
  nginx:
    image: nginx:latest
    env_file: .env
    ports:
      - ${NGX_PORT}:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - '${CQ_DATA_PATH}/data:/var/www/html'
    restart: always
